version: "3.8"
services:
  postgres:
    container_name: nodejs-boilerplate-db
    image: postgres:15
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nodejs_boilerplate_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d nodejs_boilerplate_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
